# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
    heroku: circleci/heroku@1.0.0

workflows:
    heroku_deploy:
        jobs:
            - deploy

    jobs:
    deploy:
        executor: heroku/default # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
        steps:
            - checkout
            - heroku/install # Runs the heroku install command, if necessary.
            - heroku/deploy-via-git: # Deploys branch to Heroku via git push.
                  only-branch: master # If you specify an only-branch, the deploy will not occur for any other branch.
